### ISSUE TITLE
Error with command: nvm install node

### ISSUE THREAD

**Issue by mohamedmehdigara** [FrontendMasters/intro-node-js#47]
Error msg 
====>

node.0.0
Node.js vnode.0.0 is only available in 32-bit.

**Comment by mwelwankuta** [comment]
this issue can be solved by explicitly passing in a version of node you want to install.

**Comment by dtauer** [comment]
Yes, thanks for the note! Also, this is a pretty old course and we've recently released a new version: https://frontendmasters.com/courses/node-js-v3/
